name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11 (using Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # 使用 Temurin 作为 JDK 版本   

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Build Java Application with Maven
        run: |
          cd DevOps-Project-01/shopping-cart-master
          mvn clean install

      - name: Upload WAR to S3
        run: |
          pwd
          ls -l
          cd DevOps-Project-01/shopping-cart-master
          aws s3 cp ./target/shopping-cart-0.0.1-SNAPSHOT.war s3://devops-lab022/shopping-cart.war

      - name: Deploy to Tomcat (Private Subnet) via SSM
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceIds,Values=${{ secrets.TOMCAT_INSTANCE_ID }}" \
            --parameters 'commands=["aws s3 cp s3://devops-lab022/shopping-cart.war /opt/tomcat/webapps/shopping-cart.war", "systemctl restart tomcat"]'
